
-- ==================================================
-- E-COMMERCE SALES AND CUSTOMER ANALYSIS
-- ==================================================

-- 1.Find the total number of customers from each country

SELECT 
    country, 
	COUNT(*) AS total_customers
FROM customers
GROUP BY country
ORDER BY total_customers DESC;

-- 2.How many different products are there in each category

SELECT 
   category,
   COUNT(product_id) AS total_products
FROM products
GROUP BY category
ORDER BY total_products DESC; 

-- 3.Find the number of orders placed by each customer

SELECT c.customer_id,c.country,COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o 
   ON c.customer_id=o.customer_id
GROUP BY c.customer_id,c.country
ORDER BY total_orders DESC;   

-- 4.Find the lowest-priced product

select p.product_id,p.product_name,min(oi.price) as lowest_price
from products p 
join order_items oi
   on p.product_id=oi.product_id
group by p.product_id,p.product_name
order by lowest_price
limit 1;

-- 5.Find the highest-priced product
select p.product_id,p.product_name,max(oi.price) as highest_price
from products p 
join order_items oi
   on p.product_id=oi.product_id
group by p.product_id,p.product_name
order by highest_price desc
limit 1;   

-- 6. Find revenue generated by each category

select p.category,sum(oi.quantity *oi.price) as total_revenue
from products p 
join order_items oi
   on p.product_id=oi.product_id
join orders o 
   on oi.order_id=o.order_id
where o.status='Completed'
group by p.category
order by total_revenue desc;

-- 7.Find total revenue generated by each product

select p.product_id,p.product_name,sum(oi.quantity*oi.price) as total_revenue
from products p 
join order_items oi 
   on p.product_id=oi.product_id
join orders o 
   on oi.order_id=o.order_id
where o.status='Completed'
group by p.product_id,p.product_name
order by total_revenue desc;

-- 8.Find the top 5 customers by spending

select c.customer_id,c.country,sum(oi.quantity*oi.price) as total_spent
from customers c 
join orders o
  on c.customer_id=o.customer_id
join order_items oi
  on o.order_id=oi.order_id
where o.status ='Completed'
group by c.customer_id,c.country
order by total_spent desc
limit 5;  


-- 9.Find the top 5 products by quantity sold

select p.product_id,p.product_name,sum(oi.quantity) as total_units
from products p 
join order_items oi 
  on p.product_id=oi.product_id
join orders o 
   on oi.order_id=o.order_id
where o.status ='Completed'
group by p.product_id,p.product_name
order by total_units desc
limit 5;

-- 10.Find customers who have never placed an order

select c.customer_id,c.country
from customers c 
left join orders o 
  on c.customer_id=o.customer_id
where o.order_id is null;

-- 11.Find products that have never been sold

select p.product_id,p.product_name,p.category
from products p 
left join order_items oi
  on p.product_id=oi.product_id
where oi.product_id is null;  

-- 12.Find monthly revenue

select 
    year(o.order_date) as year,
    month(o.order_date) as month,
    sum(oi.quantity*oi.price) as monthly_revenue
from orders o 
join order_items oi 
    on o.order_id=oi.order_id
where o.status='Completed'
group by 
   year(o.order_date),
   month(o.order_date)
order by year,month;   


-- 13.Find the most recent order of each customer

select customer_id,max(order_date) as latest_order_date
from orders
group by customer_id
order by latest_order_date desc;

-- 14.Find the first order of each customer

select customer_id,min(order_date) as first_order_date
from orders
group by customer_id
order by first_order_date;  

-- 15. Find the best-selling category

select p.category,sum(oi.quantity)as total_units
from products p 
join order_items oi 
   on p.product_id=oi.product_id
join orders o 
  on oi.order_id=o.order_id
where o.status='Completed'
group by p.category
order by total_units desc
limit 1;  